COUNTRIES = {
  "United States of America": "united states",
  "China - Taiwan": "taiwan",
  "China - Hong Kong SAR": "hong kong",
  "Korea (Republic of)": "south korea",
  "Belgium - Flemish Community": "belgium",
  "Belgium - French Community": "belgium",
  "MACAU": "macau",
  "China - Macao SAR": "macau",
  "Venezuela (Bolivarian Republic of)": "venezuela",
  "TRINIDAD": "trinidad and tobago",
  "Lao People's Democratic Republic": "laos",
  "Iran (Islamic Republic of)": "iran",
  "MARTINIQUE": "france",
  "France - French Guyana": "france",
  "France - French Polynesia": "france",
  "France - Guadeloupe": "france",
  "France - Martinique": "france",
  "France - New Caledonia": "france",
  "France - Reunion": "france",
  "KOREA, REPUBLIC OF": "south korea",
  "Korea (Democratic People's Republic of)": "north korea",
  "Congo (Democratic Republic)": "congo",
  "Bolivia (Plurinational State of)": "bolivia",
  "Macedonia (The Former Yugoslav Republic)": "macedonia",
  "Switezrland": "switzerland",
  "Gambia (The)": "gambia"
}
