US_STATES = {
  "AB": { "country": "canada", "province": "Alberta" },
  "AK": "Alaska",
  "AL": "Alabama",
  "AR": "Arkansas",
  "AZ": "Arizona",
  "Baltimore": "Maryland",
  "Brighton": "Colorado",
  "CA": "California",
  "CA - California": "California",
  "California(CA)": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "D.C.": "District of Columbia",
  "DC": "District of Columbia",
  "DE": "Delaware",
  "District of Col": "District of Columbia",
  "FL": "Florida",
  "GA": "Georgia",
  "HI": "Hawaii",
  "IA": "Iowa",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "KS": "Kansas",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "Lisbon": { "country": "portugal", "province": "Lisbon" },
  "M0": "Missouri",
  "MA": "Massachusetts",
  "MA - Massachuse": "Massachusetts",
  "MA.": "Massachusetts",
  "Mass.": "Massachusetts",
  "MD": "Maryland",
  "MD - Maryland": "Maryland",
  "ME": "Maine",
  "MI": "Michigan",
  "MI.": "Michigan",
  "Minn": "Minnesota",
  "Minnesota": "Minnesota",
  "MN": "Minnesota",
  "MO": "Missouri",
  "MS": "Mississippi",
  "MT": "Montana",
  "NC": "North Carolina",
  "ND": "North Dakota",
  "NE": "Nebraska",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NV": "Nevada",
  "NY": "New York",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PA": "Pennsylvania",
  "Penn": "Pennsylvania",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "TX - Texas": "Texas",
  "UT": "Utah",
  "VA": "Virginia",
  "VT": "Vermont",
  "WA": "Washington",
  "WI": "Wisconsin",
  "wisconsin": "Wisconsin",
  "WV": "West Virginia",
  "WY": "Wyoming"
}
